# Generated by Django 3.0.8 on 2020-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0725', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
