# Generated by Django 3.0.8 on 2020-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0725', '0003_pictures_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='pub_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
        ),
    ]
