# Generated by Django 3.0.8 on 2020-07-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0725', '0007_auto_20200723_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='title',
        ),
    ]
